django-polls/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    
]

django-polls/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:pk>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

django-polls/mysite/polls/models.py
# Create your models here.
import datetime

from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now        
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    def __str__(self):
        return self.choice_text

class Response(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dayandtime = models.DateField()
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.user) + " " + str(self.dayandtime) + " " + str(self.choice)

django-polls/mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.models import User
import datetime


from .models import Choice, Question, Response

class DetailView(generic.DetailView):
    model = Question
    
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())
    
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request,args,kwargs)
        taken_users = User.objects.filter(response__choice__question = pk)
        if request.user in taken_users:
            return response
        else:
            return HttpResponseRedirect(reverse('polls:detail', args))



class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
def results(request, pk):
    taken_users = User.objects.filter(response__choice__question = pk)
    if request.user in taken_users:
        question = Question.objects.get(pk=pk)
        return render(request, 'polls/results.html', {'question': question})
    else:
        return HttpResponseRedirect(reverse('polls:detail', args = pk))

def detail(request, question_id):
    #currentuser = Question.objects.filter(choice__response__user = request.user)
    usersvoted = User.objects.filter(response__choice__question = question_id)
    question = Question.objects.get(pk=question_id)

    if request.user in usersvoted:
        return render(request, 'polls/results.html', {'question': question})    
    #question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def index(request):
    pollsresponded = Question.objects.filter(choice__response__user = request.user)
    noresponse = Question.objects.filter(choice__repsonse__user = request.user)
    return render

def vote(request, question_id):
    #taken_users = User.objects.filter(response__choice__question = question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        response = Response(user = request.user, dayandtime = datetime.datetime.now(), choice = selected_choice)
        #if response in taken_users:
            #taken_users.delete(response)
        response.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

django-polls/mysite/polls/templates/polls/base_template.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title> Questionaire </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>


    <body>

        <nav class = "navbar navbar-expand-lg bg-dark navbar-dark py-3">
            <div class="container">
                <a href = "#" class = "navbar-brand" > 
                    POLLS 
                </a>
    
                <button class="navbar-toggler" type = "button" data-bs-toggle="collapse" data-bs-target = "#navmenu"> 
                    <span class="navbar-toggler-icon"></span>
                </button>
    
                <div class="collapse navbar-collapse" id = "navmenu">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a href="/polls" class="nav-link">
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/admin" class="nav-link">
                                Admin
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#local" class="nav-link">
                                Local
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#about" class="nav-link">
                                About
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            
        </nav>

        <section class="bg-dark text-light p-5 p-lg-0 pt-lg-5 m-5 text-center text-sm-start" id = "body">

            <div class="container pb-2" id = "content">
                <div class = "align-items-center">
                    <div>
                        <h1>{% block title %}{% endblock %}</h1>
                    </div>

                    <div>
                        <p>{% block description%}{% endblock %}</p>
                    </div>
                    
                    <div>
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
        </section>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </body>
</html>

django-polls/mysite/polls/templates/polls/detail.html
{% extends "polls/base_template.html" %}



{% block content %}
    {% if user.is_authenticated %}

    
        <form action="{% url 'polls:vote' question.id %}" method="post" style="margin-bottom: 20px;">
            {% csrf_token %}
            <fieldset>
                <legend><h1>{{ question.question_text }}</h1></legend>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
            </fieldset>
            <input type="submit" value="Vote">
        </form>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">Log In</a>
    {% endif %}


    
{% endblock %}


django-polls/mysite/polls/templates/polls/index.html
{% extends "polls/base_template.html" %}

{% block title %} <span class="text-warning">Home page</span> {% endblock %}


{% block description%} Questions of the day. Please choose a quesiton :){% endblock %}


{% block content %}

    {% if user.is_authenticated %}

        <h3>Hi <span class="text-warning">{{ user.username }}</span>!</h3>
        
        

        {% if latest_question_list %}

            <p>Polls not yet voted on</p>

            <table class="table table-dark table-hover">
            
                
                {% for question in latest_question_list %}

            
                    {% if choice.response.choice == null%}
                        <tr><td><a href="{% url 'polls:detail' question.id %}" style = "color: beige; text-decoration: none;">{{ question.question_text }}</a>
                        </td></tr>
                    {% endif %}

                {% endfor %}

            </table>
        {% endif %} 

            {% if latest_question_list %}

            <p>Polls voted on: click to see results</p>

            <table class="table table-dark table-hover">
            
                
            {% for question in latest_question_list %}

            
            {% if choice.response.choice %}
            <tr><td><a href="{% url 'polls:detail' question.id %}" style = "color: beige; text-decoration: none;">{{ question.question_text }}</a>
            </td></tr>
            {% endif %}

            {% endfor %}
            
            </table>

            {% if latest_question_list %}

            <p>ALL POLLS</p>

            <table class="table table-dark table-hover">
            
                
            {% for question in latest_question_list %}

            
            <tr><td><a href="{% url 'polls:detail' question.id %}" style = "color: beige; text-decoration: none;">{{ question.question_text }}</a>
            </td></tr>

            {% endfor %}
            
            </table>

            <p><a href="{% url 'logout' %}">Log Out</a></p>
            
            {% else %}
                <p>No polls are available.</p>
            {% endif %}

        {% load static %}
        
        
    {% else %}
        <p>You are not logged in so you cannot access the polls :'(</p>
        <a href="{% url 'login' %}">Log In</a>
    {% endif %}

    
    

{% endblock %}

django-polls/mysite/polls/templates/polls/results.html
{% extends "polls/base_template.html" %}

{% block title %} {{ question.question_text }}: Results {% endblock %}

{% block content %}
    {% if user.is_authenticated %}
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.response_set.count }} vote{{ choice.response_set.count|pluralize }}</li>
        {% endfor %}
    </ul>
    
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">Log In</a>
    {% endif %}

    
{% endblock %}

django-polls/mysite/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

django-polls/mysite/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}